/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RxjsCounter {
        /**
          * Amount of time in ms the onCountChange event will be debounced.
         */
        "dueTime": number;
    }
}
declare global {
    interface HTMLRxjsCounterElement extends Components.RxjsCounter, HTMLStencilElement {
    }
    var HTMLRxjsCounterElement: {
        prototype: HTMLRxjsCounterElement;
        new (): HTMLRxjsCounterElement;
    };
    interface HTMLElementTagNameMap {
        "rxjs-counter": HTMLRxjsCounterElement;
    }
}
declare namespace LocalJSX {
    interface RxjsCounter {
        /**
          * Amount of time in ms the onCountChange event will be debounced.
         */
        "dueTime"?: number;
        "onCountChange"?: (event: CustomEvent<number>) => void;
    }
    interface IntrinsicElements {
        "rxjs-counter": RxjsCounter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rxjs-counter": LocalJSX.RxjsCounter & JSXBase.HTMLAttributes<HTMLRxjsCounterElement>;
        }
    }
}
